"use client";

import { motion } from "framer-motion";
import { BrainCircuit, Trophy, LineChart, Users } from "lucide-react";
import Image from "next/image";

const features = [
  {
    name: "AI Recommendations",
    description: "Personalized, actionable insights generated by our advanced AI engine based on your specific lifestyle.",
    icon: BrainCircuit,
    imageUrl: "/feature-ai.png",
  },
  {
    name: "Smart Challenges",
    description: "Join challenges like 'Plastic-free week' or 'Bike-to-work' and earn XP for real-world actions.",
    icon: Trophy,
    imageUrl: "/feature-challenges.png",
  },
  {
    name: "Deep Analytics",
    description: "Track your transportation, food, and energy emissions with beautiful interactive charts.",
    icon: LineChart,
    imageUrl: "/feature-analytics.png",
  },
  {
    name: "Community Leaderboard",
    description: "Compare your progress with friends and top sustainability champions globally.",
    icon: Users,
    imageUrl: "/feature-leaderboard.png",
  },
];

export function Features() {
  return (
    <section id="features" className="py-32 bg-background/50 backdrop-blur-sm overflow-hidden relative z-10">
      <div className="absolute inset-0 bg-[linear-gradient(to_bottom,var(--background),transparent_10%,transparent_90%,var(--background))] pointer-events-none z-10"></div>
      
      <div className="container mx-auto px-4 relative z-20">
        <div className="text-center mb-32">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            className="inline-flex items-center rounded-full border border-primary/20 bg-primary/10 px-4 py-1.5 text-sm font-semibold text-primary mb-6"
          >
            Capabilities
          </motion.div>
          <motion.h2 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ delay: 0.1 }}
            className="text-5xl md:text-7xl font-black tracking-tight mb-6 text-foreground"
          >
            Powerful tools for a <br className="hidden md:block"/>
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-emerald-400">greener tomorrow</span>
          </motion.h2>
        </div>

        <div className="space-y-40">
          {features.map((feature, index) => {
            const isEven = index % 2 === 0;
            return (
              <div key={feature.name} className={`flex flex-col ${isEven ? 'lg:flex-row' : 'lg:flex-row-reverse'} items-center gap-16 lg:gap-24`}>
                <motion.div
                  initial={{ opacity: 0, x: isEven ? -50 : 50 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true, margin: "-200px" }}
                  transition={{ duration: 0.8, ease: "easeOut" }}
                  className="flex-1 space-y-8"
                >
                  <div className="inline-flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10 shadow-[0_0_30px_rgba(16,185,129,0.2)]">
                    <feature.icon className="h-8 w-8 text-primary" />
                  </div>
                  <h3 className="text-4xl md:text-5xl font-black text-foreground tracking-tight">{feature.name}</h3>
                  <p className="text-xl text-muted-foreground leading-relaxed max-w-lg">
                    {feature.description}
                  </p>
                </motion.div>

                <motion.div
                  initial={{ opacity: 0, scale: 0.9, rotateY: isEven ? 15 : -15 }}
                  whileInView={{ opacity: 1, scale: 1, rotateY: 0 }}
                  viewport={{ once: true, margin: "-200px" }}
                  transition={{ duration: 0.8, ease: "easeOut" }}
                  className="flex-1 w-full"
                >
                  {/* Decorative Abstract Graphic Representation */}
                  <div className="relative aspect-square md:aspect-[4/3] w-full rounded-[2.5rem] bg-gradient-to-br from-primary/5 to-accent/5 border border-white/5 overflow-hidden group">
                    <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-primary/20 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700"></div>
                    <div className="absolute inset-0 flex items-center justify-center p-6 md:p-12">
                      <div className="absolute inset-0 bg-gradient-to-t from-background/90 via-background/20 to-transparent z-10" />
                      {feature.imageUrl && (
                        <Image 
                          src={feature.imageUrl} 
                          alt={feature.name} 
                          fill
                          className="object-cover"
                          sizes="(max-width: 768px) 100vw, 50vw"
                        />
                      )}
                    </div>
                  </div>
                </motion.div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
