import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

export default function TermsOfService() {
  return (
    <div className="flex min-h-screen flex-col relative overflow-hidden bg-background">
      {/* Background Gradient */}
      <div className="fixed inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary/10 via-background/20 to-background/50 pointer-events-none -z-10" />

      <Navbar />
      
      <main className="flex-1 container mx-auto px-4 py-32 max-w-4xl relative z-10">
        <div className="bg-card/80 backdrop-blur-md rounded-3xl p-8 md:p-12 border shadow-sm">
          <h1 className="text-4xl md:text-5xl font-black mb-6 text-foreground tracking-tight">Terms of Service</h1>
          <p className="text-muted-foreground mb-10 font-medium">Last updated: {new Date().toLocaleDateString()}</p>
          
          <div className="space-y-8 text-muted-foreground leading-relaxed">
            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">1. Acceptance of Terms</h2>
              <p>By accessing and using EcoTrace AI, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.</p>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">2. Description of Service</h2>
              <p>EcoTrace AI provides intelligent tools to track, calculate, and offset personal and enterprise carbon footprints. The calculations provided are estimations generated by AI models and should be used as guidance, not legal regulatory reporting.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">3. User Accounts</h2>
              <p>To use certain features, you must register for an account. You agree to provide accurate information and keep your credentials secure. You are responsible for all activity under your account.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">4. Limitation of Liability</h2>
              <p>EcoTrace AI shall not be liable for any indirect, incidental, special, consequential or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly.</p>
            </section>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
}
