import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { BrainCircuit, CheckCircle2, TrendingDown } from "lucide-react";
import { Button } from "@/components/ui/button";

export default async function RecommendationsPage() {
  const session = await getServerSession(authOptions);
  if (!session || !session.user) return null;

  const recommendations = await prisma.recommendation.findMany({
    where: { userId: session.user.id },
    orderBy: { impactScore: 'desc' },
  });

  const completedCount = recommendations.filter(r => r.isCompleted).length;
  const pending = recommendations.filter(r => !r.isCompleted);

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div>
        <h1 className="text-3xl font-bold flex items-center gap-3">
          <BrainCircuit className="h-8 w-8 text-emerald-500" />
          AI Recommendations
        </h1>
        <p className="text-muted-foreground mt-2 text-lg">Personalized, actionable insights generated by our advanced AI engine based on your specific lifestyle.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="bg-emerald-500/10 border-emerald-500/20 backdrop-blur-xl shadow-lg relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-emerald-500/10 to-transparent opacity-50" />
          <CardHeader className="pb-2 relative z-10">
            <CardTitle className="text-sm font-medium text-emerald-400">Actions Completed</CardTitle>
          </CardHeader>
          <CardContent className="relative z-10">
            <div className="text-4xl font-black text-emerald-500">{completedCount} <span className="text-xl font-normal text-emerald-500/50">/ {recommendations.length}</span></div>
          </CardContent>
        </Card>
        
        <Card className="bg-blue-500/10 border-blue-500/20 backdrop-blur-xl shadow-lg md:col-span-2 flex flex-col justify-center relative overflow-hidden group">
          <div className="absolute inset-0 bg-gradient-to-br from-blue-500/10 to-transparent opacity-50 group-hover:opacity-100 transition-opacity duration-500" />
          <CardContent className="p-6 relative z-10">
            <p className="text-blue-300 font-medium text-lg">Completing these pending actions could reduce your footprint by an estimated <strong className="text-blue-400 text-2xl px-1">{pending.reduce((acc, r) => acc + r.impactScore, 0)} kg CO₂e</strong> per month.</p>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-4">
        {pending.length > 0 ? pending.map((rec) => (
          <div key={rec.id} className="p-6 rounded-2xl border border-white/5 bg-card/40 backdrop-blur-xl shadow-lg hover:shadow-emerald-500/10 hover:border-emerald-500/30 transition-all duration-300 flex flex-col sm:flex-row sm:items-center gap-6 group">
            <div className="h-16 w-16 rounded-xl bg-emerald-500/10 text-emerald-500 flex items-center justify-center flex-shrink-0 group-hover:scale-110 group-hover:bg-emerald-500/20 transition-all duration-300 shadow-[0_0_15px_rgba(16,185,129,0.2)]">
              <TrendingDown className="h-8 w-8" />
            </div>
            <div className="flex-1 space-y-1">
              <h3 className="text-xl font-bold text-foreground group-hover:text-emerald-400 transition-colors">{rec.title}</h3>
              <p className="text-muted-foreground/80">{rec.description}</p>
              <div className="pt-3 flex items-center gap-3">
                <span className="text-sm font-bold text-emerald-400 bg-emerald-500/10 px-3 py-1 rounded-full border border-emerald-500/30 shadow-[0_0_10px_rgba(16,185,129,0.1)]">
                  Impact: -{rec.impactScore} kg
                </span>
                <span className="text-sm font-medium text-blue-400 bg-blue-500/10 px-3 py-1 rounded-full border border-blue-500/30">
                  Medium Effort
                </span>
              </div>
            </div>
            <div className="flex-shrink-0 mt-4 sm:mt-0">
              <form action={async () => {
                "use server";
                const { markRecommendationDone } = await import("@/app/actions/recommendations");
                await markRecommendationDone(rec.id);
              }}>
                <Button type="submit" variant="outline" className="w-full sm:w-auto h-12 rounded-xl font-bold border-emerald-500/30 bg-emerald-500/5 hover:bg-emerald-500 hover:text-white hover:border-emerald-500 transition-all duration-300 shadow-[0_0_15px_rgba(16,185,129,0.1)] hover:shadow-[0_0_20px_rgba(16,185,129,0.4)]">
                  Mark as Done <CheckCircle2 className="ml-2 h-5 w-5" />
                </Button>
              </form>
            </div>
          </div>
        )) : (
          <div className="text-center py-20 px-4 rounded-3xl bg-muted/30 border border-dashed">
            <BrainCircuit className="h-16 w-16 mx-auto text-muted-foreground/30 mb-4" />
            <h3 className="text-xl font-bold mb-2">You're all caught up!</h3>
            <p className="text-muted-foreground mb-6">Our AI is analyzing your latest data to generate new insights.</p>
            <form action={async () => {
              "use server";
              const { generateMoreInsights } = await import("@/app/actions/recommendations");
              await generateMoreInsights();
            }}>
              <Button type="submit" className="bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-bold shadow-[0_0_15px_rgba(16,185,129,0.3)]">
                Discover More Insights
              </Button>
            </form>
          </div>
        )}
      </div>
    </div>
  );
}
